blueprint:
  name: automatic light switch based on Sun
  description: Turn lights on when the sun goes down.
  domain: automation
  input:
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light

mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: sun.sun

action:
- choose:
  - conditions:
    - condition: state
      entity_id: sun.sun
      state: "above_horizon"
    sequence:
    - service: light.turn_off
      target: !input light_target
      data:
        transition: 2
  - conditions:
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"
    sequence:
    - service: light.turn_on
      target: !input light_target 
      data:
        transition: 2
